"""model fix6

Revision ID: 0430ac134c49
Revises: 22e5ed22a813
Create Date: 2023-11-07 01:13:56.211148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0430ac134c49'
down_revision: Union[str, None] = '22e5ed22a813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works', 'salary',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works', 'salary',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    # ### end Alembic commands ###
