"""model fix5

Revision ID: 22e5ed22a813
Revises: 6bb0f1f6f768
Create Date: 2023-11-07 00:52:44.725698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22e5ed22a813'
down_revision: Union[str, None] = '6bb0f1f6f768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'id')
    # ### end Alembic commands ###
