"""model fix2

Revision ID: 372e4a35710e
Revises: dce034be977f
Create Date: 2023-11-07 00:48:17.682745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372e4a35710e'
down_revision: Union[str, None] = 'dce034be977f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('location', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_works_location'), 'works', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_works_location'), table_name='works')
    op.drop_column('works', 'location')
    # ### end Alembic commands ###
