"""model fix3

Revision ID: 6bb0f1f6f768
Revises: 372e4a35710e
Create Date: 2023-11-07 00:50:54.425816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6bb0f1f6f768'
down_revision: Union[str, None] = '372e4a35710e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('id_jod', sa.Integer(), nullable=False))
    op.drop_index('ix_works_id', table_name='works')
    op.create_index(op.f('ix_works_id_jod'), 'works', ['id_jod'], unique=False)
    op.drop_column('works', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_works_id_jod'), table_name='works')
    op.create_index('ix_works_id', 'works', ['id'], unique=False)
    op.drop_column('works', 'id_jod')
    # ### end Alembic commands ###
